import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Toast from "@/components/Toast";
import "keen-slider/keen-slider.min.css";

const poppins = localFont({
  src: "./assets/fonts/Poppins-Light.ttf",
  variable: "--font-poppins",
  weight: "400",
});

const playfair = localFont({
  src: "./assets/fonts/Playfair_9pt-Black.ttf",
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Better Vibes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${poppins.variable}`}>
        <Toast />
        {children}
      </body>
    </html>
  );
}
