export const AUTH_TOKEN_EXPIRES = Date.now() + 180 * 24 * 60 * 60 * 1000;
export const musicsGenres = [
  "Pop",
  "Rock",
  "Hip Hop",
  "Rap",
  "R&B",
  "Soul",
  "Jazz",
  "Blues",
  "Country",
  "Classical",
  "Electronic",
  "Dance",
  "House",
  "Trance",
  "Techno",
  "Dubstep",
  "Reggae",
  "Reggaeton",
  "Latin",
  "Afrobeat",
  "Indie",
  "Alternative",
  "Folk",
  "Metal",
  "Punk",
  "Funk",
  "Disco",
  "Lo-fi",
  "Chillhop",
  "Soundtrack",
  "K-Pop",
  "J-Pop",
  "EDM",
  "Gospel",
  "Opera",
  "Trap",
  "Drill",
  "Ambient",
  "Grime",
  "Ska",
  "Synthwave",
  "Industrial",
  "Experimental",
  "Acoustic",
  "Instrumental",
];

export const categoriesArr: { title: string; imagePath: string }[] = [
  {
    title: "Chill",
    imagePath: "/images/category-chill.jpg",
  },
  {
    title: "Energetic",
    imagePath: "/images/category-energetic.jpg",
  },
  {
    title: "Party",
    imagePath: "/images/category-party.jpg",
  },
  {
    title: "Rainy Day",
    imagePath: "/images/category-rainy-day.jpg",
  },
  {
    title: "Sad",
    imagePath: "/images/category-sad.jpg",
  },
  {
    title: "Sleep",
    imagePath: "/images/category-sleep.jpg",
  },
  {
    title: "Study",
    imagePath: "/images/category-study.jpg",
  },
];
